### ISSUE TITLE
Make sure to add Shadow DOM support when it will land in React

### ISSUE THREAD

**Issue by roman01la** [PixelsCommander/ReactiveElements#15]
I've noticed that [React component currently does render straight into custom element itself](https://github.com/PixelsCommander/ReactiveElements/blob/master/src/reactive-elements.js#L19). There's Shadow DOM thing which is a part of Web Components spec, the benefit of it is encapsulation of the functionality.

React doesn't support Shadow DOM yet, but it seems there's [some WIP already happening](https://github.com/facebook/react/pulls?q=is%3Apr+is%3Aopen+shadow).

Just a reminder note ;)

**Comment by rektide** [comment]
I'd like for some way to be able to specify whether or not to render into Shadow DOM. I like being able to create Custom Elements, but in most cases I'd prefer rendering into the DOM than into Shadow DOM.

**Comment by ryanpcmcquen** [comment]
What is the status of this?

**Comment by jackfranklin** [comment]
Closing this because it's very old, but please let me know if you would like this reopened :)

**Comment by bboydflo** [comment]
oh yes, I would like to know how to render into shadow root. That's waht I actually wanted to achieve by using this library.
