### ISSUE TITLE
HTML5 attributes aren't case sensitive

### ISSUE THREAD

**Issue by reggi** [PixelsCommander/ReactiveElements#16]
I tried converting this [react timer component](https://github.com/uken/react-countdown-timer) using this library, and I noticed that there is a prop `initialTimeRemaining` so I used it something like this.

```
<react-timer initialTimeRemaining="60000"> </react-timer>
```

There were two problems with this.

1) HTML5 doesn't support casing like this in attributes
2) The prop is [required to be a number](https://github.com/uken/react-countdown-timer/blob/master/countdown_timer.jsx#L21)

I would love it if reactive elements could handle the attribute mapping. Thoughts? I would love it if we could get to a point of having transparency between [react-native] and [react as web-components].

**Comment by PixelsCommander** [comment]
There was an issue on that https://github.com/PixelsCommander/ReactiveElements/issues/3, just use one of delimiters ':', '-', '_' to specify uppercased letter

**Comment by reggi** [comment]
@PixelsCommander that works, how do you declare a attribute as a number though?

**Comment by PixelsCommander** [comment]
Do you mean attribute value or attribute name?

**Comment by reggi** [comment]
@PixelsCommander Attribute value.

**Comment by PixelsCommander** [comment]
There is no way to specify the type of attribute in ReactiveElements / Custom Elements / HTML specifications. RE supports pointing to objects as a ReactJS way of setting attributes and setting strings is a HTML way.

There are few propositions on how it could be implemented, would like your opinion on them:
Hungarian notation: n-alpha attribute mean nAlpha property which would be converted to integer by reactive elements lib;
Type schema attribute: type-alpha="integer" would mean that alpha property will be converted to integer;
The last but not the least: if you expect that property could be set from attribute - use parseInt on render etc.

**Comment by PixelsCommander** [comment]
Just added attributeChanged callback support https://github.com/PixelsCommander/ReactiveElements/blob/master/example/jsx/my-reactive-element.jsx#L11 it can potentially help you. The rest of approaches I see are less elegant.

**Comment by reggi** [comment]
@PixelsCommander I can't get this to log anything:

```
attributeChanged: function(name, oldValue, newValue) {
      console.log('Attribute ' + name + ' was changed from ' + oldValue + ' to ' + newValue);
  },
```

However I don't think this is the answer.

What I want is interoperability between native react components that already exist and making them stand alone web components. __Preferably without editing the native react components source.__


In an ideal world I would love to see a reactive-element-CLI that would act like this:

```
npm install uken/react-countdown-timer --save
npm install reactive-element --save
reative-register react-countdown-timer as react-timer
```

Then I can use `<react-timer>` in my HTML.

> __note__: lets ignore that `uken/react-countdown-time` isn't a proper node module it's in `JSX` and doesn't export `main` in `package.json`

But if there's no support on the reactive-element to map / handle the attribute issue without editing the elements code itself it's going to be nearly impossible to have this level of flexibility with native react components. 

Hope this clears up why this is really important to me and the ecosystem.

**Comment by reggi** [comment]
@PixelsCommander I just got the idea from [this](https://github.com/desandro/masonry/blob/master/README.mdown#in-html) that what we could do here is have a `reactive` attribute that could compute a json string, like this.

```html
<react-timer reactive='{"initialTimeRemaining": 5000}'>
</react-timer>
```

This would solve the issue of [attribute casing] issue and the [required integer type] issue and would validate for [the timer element](https://github.com/uken/react-countdown-timer/blob/master/countdown_timer.jsx#L21) and fulfill it's `propTypes` / `initialTimeRemaining: React.PropTypes.number.isRequired`.

The only problem with this would be if there was a conflict with a library that had a `prop` with the keyword `reactive`.

Would love your thoughts on this!!

**Comment by reggi** [comment]
@PixelsCommander I keep forgetting that the casing issue is solved. Still have the issue of passing this through as an number and not a string.

```
<react-timer initial-time-remaining="600000">
</react-timer>
```

**Comment by PixelsCommander** [comment]
The last one looks nice, however I have a proposition to make it a bit more generic through a new convention - third parameter extends component. Feature we are talking about will look like this:

```registerReact('react-timer', timerClass, {
  "attributeChanged": function(name, oldValue, newValue) {
      if (name === 'initialTimeRemaining') {
          this.props['initialTimeRemaining'] = parseInt(newValue);
      }
  }
});```

**Comment by reggi** [comment]
@PixelsCommander I agree i like the third param extending the component.

My concerns / confusion is:

* Is `attributeChanged` an event or a loop?
* Why I'm only getting one `name` variable at a time (unless it's an event / loop)?
* I don't understand `oldValue` / `newValue`, why would you have access to these here, when `newValue` isn't created yet?
* I'm a little worried that I don't have access to all the attributes as one variable here.

Personally I'd like to get rid of the `if`'s and see something like this, understandable if it's not doable though.

```HTML
<react-timer initial-time-remaining="600000" format="DD Days, MM Minutes Left">
</react-timer>
```

```javascript
registerReact('react-timer', timerClass, {
    "modifyAttributes": function(attributes) {
         // string to number 
         this.props['initialTimeRemaining'] = parseInt(attributes["initialTimeRemaining"]);
         // uses attribute to create new new function prop 
         this.props['formatFunc'] = function(timeRemaining){
              return moment(timeRemaining, "YY:DD:MM").format(attributes['format'])
         }
    }
});
```

All in all I would like the ability to [modify] and [add] attributes / properties and I really don't care how it's done. :rainbow: :smile: :diamonds: :crescent_moon: :bear: :cactus:

**Comment by PixelsCommander** [comment]
'''attributeChanged''' callback is a part of web components specification, 
there is only one variable since you can change only one attribute at a time by '''node.setAttribute''',
'''newValue''' is known since callback called immediately after '''setAttribute(name, value)''' executed,
you have access to all properties via '''this.props'''

**Comment by PixelsCommander** [comment]
Sure, I would like to add more sugar on top of ReactiveElements but want to stick to specifications as much as possible and be cautious in API implementation. Will implement extending this week and then will see on how it goes with this approach.

**Comment by PixelsCommander** [comment]
Fck, now I see, you need something for initialization and attributeChanged will not do that

**Comment by PixelsCommander** [comment]
There is a new issue for that https://github.com/PixelsCommander/ReactiveElements/issues/19
