### ISSUE TITLE
Pass JSON as attribute value

### ISSUE THREAD

**Issue by PixelsCommander** [PixelsCommander/ReactiveElements#17]
Since we are parsing attribute value for {{}} sequence it is impossible to pass JSON - it is being interpreted as a pointer to value. 

We need a heuristic to determine is it a JSON or pointer.

**Comment by FractalizeR** [comment]
Can't we just use `try {JSON.parse(...)} catch {}` ?

**Comment by FractalizeR** [comment]
Or we can use JSX notation: http://stackoverflow.com/a/23409124/173677

As far as I understand, this is perfectly valid notation in JSX:
```
style={{"height" : "100%", "width" : "50%"}}
```

**Comment by PixelsCommander** [comment]
Both could work. However using practices from React is more appreciated.

**Comment by FractalizeR** [comment]
Ok ;) Created a small PR: https://github.com/PixelsCommander/ReactiveElements/pull/20
Please review.

**Comment by PixelsCommander** [comment]
Your PR is a bit unclear and lacking of tests. Please, review my comments.

**Comment by PixelsCommander** [comment]
Fixed in 0.4.7

**Comment by FractalizeR** [comment]
I'm not sure it will work with json data enclosed into square brackets. Will it?

**Comment by PixelsCommander** [comment]
Give an example

**Comment by FractalizeR** [comment]
`{key:  value}` is a valid json. I can pass it to the attribute as `{{key:  value}}`, right? But `['value1', 'value2']`is also a valid JSON object. How to pass it to attribute? Will `{['value1', 'value2']}` work?

**Comment by PixelsCommander** [comment]
Fixed

**Comment by FractalizeR** [comment]
Thanks.
