### ISSUE TITLE
After changing attributes it is not always possible to change props directly or virce versa

### ISSUE THREAD

**Issue by PixelsCommander** [PixelsCommander/ReactiveElements#2]
At the moment it is recommended to use only one approach of these two in project

**Comment by FractalizeR** [comment]
Can you please elaborate? "Directly" means outside of react component, right?

**Comment by PixelsCommander** [comment]
Check out the following one: buttons here http://pixelscommander.com/polygon/reactive-elements/example/#.VNnUzmTF9Mk represent different approaches of changing props: via node.props, via attributes and via method. After clicking few rounds buttons stop work.

**Comment by FractalizeR** [comment]
Isn't this happening because of direct properties modification? They must be immutable actually:
> So far, each component has rendered itself once based on its props. props are immutable: they are passed from the parent and are "owned" by the parent.

http://facebook.github.io/react/docs/tutorial.html

Also I can see a special method for setting properties inside a ReactComponent.js named setProps(). It is now marked as deprecated, but from it's code it doesn't seem that you can change props by just assignment.

**Comment by PixelsCommander** [comment]
No it is happening because of missing binding. Since we are making operations on node and not on React component all methods are binded and all properties are transfered from React component to node with getters / setters. Seems that one of ways of changing values rewrites getters setters and breaks access to properties in this way.

**Comment by FractalizeR** [comment]
I see, thanks for explanation.

**Comment by jackfranklin** [comment]
Closing this because it's very old, but please let me know if you would like this reopened :)
