### ISSUE TITLE
Set react props of any type without react specific api

### ISSUE THREAD

**Issue by kof** [PixelsCommander/ReactiveElements#25]
It would be nice when we use custom elements to stick to the dom api, but setAttribute allows only string values.

Any ideas how to do basically setProps but using dom api? E.g. via data api?

**Comment by FractalizeR** [comment]
I don't think it's correct. To me HTML attributes, including data ones are props, not state. And React docs warn you about not mixing those things up: http://facebook.github.io/react/tips/props-in-getInitialState-as-anti-pattern.html

**Comment by kof** [comment]
my bad, better fit is props.data

**Comment by kof** [comment]
Any other ideas how to use reactive element, without to call react specific methods like setProps on element and without serialization overhead to string ... basically using setAttribute we can't pass anything else than string, right?

**Comment by FractalizeR** [comment]
If you want to mutate component's state, then you should use Flux-like workflow. Look at [ReFlux.js](https://github.com/spoike/refluxjs)

**Comment by kof** [comment]
Well I want rather to mutate components props but with values of any type and without to use reacts specific api ...

**Comment by PixelsCommander** [comment]
Working in a flux way on web components is amazing idea. 
Is there any vision on how it could look like?

**Comment by kof** [comment]
its just not a replacement for what I am asking for ...

**Comment by PixelsCommander** [comment]
Sorry

**Comment by FractalizeR** [comment]
@PixelsCommander Speaking about RefluxJS you just need to inject datastore into a component with props: https://github.com/spoike/refluxjs#react-component-example

**Comment by kof** [comment]
It doesn't matter any more as props are immutable in react 0.13
