### ISSUE TITLE
Support all custom element lifecycle callbacks

### ISSUE THREAD

**Issue by rektide** [PixelsCommander/ReactiveElements#33]
Currently only the `attributeChanged` custom lifecycle callback is supported by Reactive Elements, but Custom Elements support a [a number of other types of lifecycle events](http://w3c.github.io/webcomponents/spec/custom/#types-of-callbacks):
- created
- detached (cause a componentWillUnmount?)
- attached (cause a componentDidMount?)

**Comment by aindlq** [comment]
Why is it required to have custom callbacks like attributeChanged. I would say that attributeChanged is react's componentWillReceiveProps, created is corresponds to componentWillMount, etc. So all that we need to do is to properly propagate new props  to enable componentWillReceiveProps. Are there any advantages for having custom APIs?

**Comment by PixelsCommander** [comment]
Agree but it is not a custom API it is a web components API. Will be used only in case React component is web componentized.

**Comment by kristianmandrup** [comment]
Can this issue be closed!?

**Comment by jackfranklin** [comment]
Closing this because it's very old, but please let me know if you would like this reopened :)
