### ISSUE TITLE
JSON in attribute, why single quotes are replaced by double quotes?

### ISSUE THREAD

**Issue by aindlq** [PixelsCommander/ReactiveElements#37]
Are there any good reasons why single quotes are replaced by double quotes in 

```
value = JSON.parse(jsonMatches[0].replace(/^{|}$/g, '').replace(/'/g, '"'));
```

My felling is that this is for the case when object field name is quoted using single quotes like:
```
{'obj': 'value'}
```
right? If this is the case then it is not a valid json according to http://rfc7159.net/rfc7159 and http://www.json.org/, only double quotes are allowed.

Anyway I think that it is not a very good idea to silently replace quotes because it can break data where single quotes are relevant. What do you think?

**Comment by PixelsCommander** [comment]
I agree Artem, this should be fixed

**Comment by PixelsCommander** [comment]
@codejet what do you think on this one?

**Comment by codejet** [comment]
@PixelsCommander just removing the `replace` doesn't solve the issue if you still want to prevent ending up with invalid json like `'status': "I'm active"` (if that was your initial intention). you need a proper regex then.

**Comment by aindlq** [comment]
@codejet sorry, but I don't get it, the library just consume json. Basically just parse string from data attribute as json object and pass it to react component. If json is invalid then it is problem of a caller. We can't do anything about it.

**Comment by codejet** [comment]
i'm not sure why this was originally added, but you're actually right. if the json is invalid, `JSON.parse` will throw an error, which makes it clear that there is something wrong with the input. trying to ensure correct json is rather not reasonable here.
