### ISSUE TITLE
Consider collaboration

### ISSUE THREAD

**Issue by Wildhoney** [PixelsCommander/ReactiveElements#39]
I'm the author of [Maple](https://github.com/Wildhoney/Maple.js), which is very similar in its philosophy to `ReactiveElements`, although with a different approach to achieving it.

Would be great to see if we could collaborate and take this forwards into a larger project :+1: 

Thoughts?

**Comment by PixelsCommander** [comment]
Hi man

Maple is a nice one. Let`s be friends =) 

I have some ideas on what could be in the middle of our kids. Not sure it is the most convenient place to discuss. Lets have a skype call tomorrow or next week.

**Comment by Wildhoney** [comment]
Agreed &ndash; sound good! Skype is adam.timberlake@gmail.com
