### ISSUE TITLE
Support react 0.13

### ISSUE THREAD

**Issue by kof** [PixelsCommander/ReactiveElements#40]
We should consider breaking changes to support it.

https://github.com/facebook/react/blob/master/CHANGELOG.md#breaking-changes

**Comment by kof** [comment]
Ok now as we have https://github.com/PixelsCommander/ReactiveElements/commit/1e31689bbca23acfeb971d7f23ca280954499142 merged we need to go next:

1. _content property looks like a hack, if its intended to be used it shoudn't be prefixed by  underscore
1. _content should be actually a document fragment instead of an element
1. I would think of a better name than content, for e.g. children
1. React doesn't want us to use imperative style. Basically all component methods are   internal and shoudn't be used from the outside. https://github.com/jsstyles/react-jss/issues/15
We have 2 ways how to put props, using element attribtues and setting element.props directly. However sometimes we need to trigger an action. I have used an imperative style for this and used components methods directly. Instead we should use an event/channel/stream. Events are already implemented, the only thing we need to do is to pass the custom element to the component. Component should listen to events on custom element and react. For this we need a name for the custom element passed via props. I would suggest `container`.

**Comment by PixelsCommander** [comment]
1 kept to prevent overlappings with real props.
2,3 fixed
4 for consideration
