### ISSUE TITLE
Support Universal Module Definition

### ISSUE THREAD

**Issue by captivationsoftware** [PixelsCommander/ReactiveElements#48]
Right now, it looks like this lib only supports CommonJS (i.e. Node-style) module definitions. Unfortunately, I don't get to make use of that on my current project. Instead, I'm using requireJS which uses AMD style definitions. It would be nice if you supported UMD, thus supporting both styles.

The fix would likely look something like this (untested): 
```
(function (root, factory) {
    if (typeof define === "function" && define.amd) {
        define(["react", "documentRegisterElement"], factory);
    } else if (typeof exports === "object") {
        module.exports = factory(require("react"), require("documentRegisterElement"));
    } else {
        root.ReactiveElements= factory(root.React, root.document.registerElement || root.document.register);
    }
}(this, function (React, documentRegisterElement) {
     var ReactiveElements = { 
         ...
    };
    return ReactiveElements;
}));
```

In the meantime, for anyone else in my predicament, in order to get ReactiveElements to work in a requireJS setup, wrap the source of the lib in the following: 
`define(function(require, exports, module) { <source> })`.

**Comment by PixelsCommander** [comment]
Hello

Could you make a pull request on that?

**Comment by captivationsoftware** [comment]
Yea, sure... I'll get it in later today probably.
