### ISSUE TITLE
Release latest version to npm.

### ISSUE THREAD

**Issue by aindlq** [PixelsCommander/ReactiveElements#49]
The latest version available on npm is 0.4.9, which is 6 months old. 
Could you please release the latest version from master to npm.

**Comment by PixelsCommander** [comment]
Hi. Have some troubles accessing keys for npm repo,  will figure out next
week.  Sorry for delay
26 авг. 2015 г. 12:00 пользователь "Artem Kozlov" <notifications@github.com>
написал:

**Comment by PixelsCommander** [comment]
Done
