### ISSUE TITLE
CustomElements and React rendering compatibility issue

### ISSUE THREAD

**Issue by kof** [PixelsCommander/ReactiveElements#51]
I stumbled over this prob recently:

In DOM changing props is sync, if you change it, you have it rendered immediately.
In react there is an update cycle. 

If I set new props and then try to execute something that expects props are already handled inside - it might fail if something inside of react component depends on the rendering loop.

Which means that we either need  a method instead of .props setter which will have a callback (same as React.render) method. Or we need something else.

**Comment by PixelsCommander** [comment]
Or callback kinda this.ready(executeFunctino);

2015-10-09 13:35 GMT+02:00 Oleg Slobodskoi <notifications@github.com>:

**Comment by kof** [comment]
yep ... onRender ...

**Comment by kof** [comment]
or onUpdate

**Comment by kof** [comment]
However a global callback per element is a hacky solution in this case because I need to know at the moment I set something when its done. Global callback will require me to have a notification system in my user code to do that.

**Comment by kof** [comment]
will create a  PR with onRender callback
