### ISSUE TITLE
render() does not accept DocumentFragment

### ISSUE THREAD

**Issue by svachalek** [PixelsCommander/ReactiveElements#56]
I'm using React 0.14.3 and Chrome 47.0.2526.106.

I'm trying to create a component that accepts child elements but it's coming in as a DocumentFragment which React will not accept (as JSX {this.props.children}), and still looking for a way to convert to something that it does accept.

Maybe a new issue with React 14? Any solution or guidance is appreciated.

**Comment by PixelsCommander** [comment]
Use ref="myRef" then var appendTarget = findDOMNode(this.refs.myRef) then appendTarget.appendChild(this.props._children)

**Comment by kulor** [comment]
@PixelsCommander I'd really like to have the ability to freely transclude by rendering `{this.props.children}` and right now with ReactiveElements, I can't find a solution (your comment here doesn't work for me, maybe a JSBin?). I've been playing around with https://github.com/greenish/react-mount which allows this but isn't as well maintained as this repo and relies on a JSXTransformer which I'm not sure if it's avoidable to support doc fragment children?

A common use case for custom elements would be to do something like:

```
regular.html:
<my-carousel>
  <slide src="http://domain/image.jpg"></slide>
  <slide src="http://domain/image2.jpg"></slide>
</my-carousel>
```

Are there plans to improve this child relationship to interop with React?

**Comment by PixelsCommander** [comment]
Transformer was deprecated a while ago and it was the only way to do it.

Let`s have a call in Skype and discuss issue. May be we can find solution for your case together. Mine skype is lp_funky

**Comment by kulor** [comment]
@PixelsCommander cool, don't suppose you are free before 5pm (BST) today?

**Comment by PixelsCommander** [comment]
Yeah, pretty busy schedule today. I ll be available from 7 to 10pm CET (seems to be 6-9pm your time).

**Comment by kulor** [comment]
@PixelsCommander we both missed each other yesterday but I keep thinking about this problem and it's a tough one. In many ways I think it's a bad idea to put the children through a JSX parser as it's going to be expensive, especially if you've got many elements. I did some research and came across both [AcornJSX](https://github.com/RReverser/acorn-jsx) which looked promising but it's going to add bloat as it's still a runtime JS parser.

Another meta question came up in my mind; how would a parser handle a child custom element with a React class behind it? E.g:

```
<react-element>
   <different-react-element></different-react-element>
</react-element>
```

Which would need to do some reverse engineering to achieve something like this behind the scenes?
```
<react-element>
   <DifferentReactElement></DifferentReactElement>
</react-element>
```

Let me know if you're around in the day for a chat (15 mins?), I'm out tonight.

**Comment by PixelsCommander** [comment]
Yeah, lets have a chat in 3.5 hours, mean 16 00 CET

2016-04-21 12:13 GMT+02:00 James Broad <notifications@github.com>:

**Comment by kulor** [comment]
@PixelsCommander perfect! I'm jcbroad on Skype

**Comment by ryanpcmcquen** [comment]
What happened with this. This functionality is vital to my team. Is there a workaround?

**Comment by PixelsCommander** [comment]
@ryanpcmcquen Do you mean rendering a document fragment?

**Comment by ryanpcmcquen** [comment]
@PixelsCommander, yes.

**Comment by jackfranklin** [comment]
We've worked around this by using a `ref` in React and then `appendChild(this.props.children)` within the component on the `ref` does work. It's not ideal though and I'd welcome thoughts on improving it.

This issue is very old but if someone would like to explore this, please open a new issue :)
