### ISSUE TITLE
Update to support recent versions of React

### ISSUE THREAD

**Issue by Elephant-Vessel** [PixelsCommander/ReactiveElements#58]
This breaks in recent versions of React since render now is located in ReactDOM, not React.

```javascript
function create(parent, props) {
    var element = React.createElement(ReactComponent, props);
    return React.render(element, parent, props.onRender);
}
```

**Comment by PixelsCommander** [comment]
Which version do you use? 

It was updated long long time ago https://github.com/PixelsCommander/ReactiveElements/blob/master/src/reactive-elements.js#L22

**Comment by Elephant-Vessel** [comment]
Oh, the problem seems to be bower. It thinks 0.5.4 is the latest version.

**Comment by Elephant-Vessel** [comment]
Would you consider updating the tags?

**Comment by PixelsCommander** [comment]
Sure, done.

**Comment by Elephant-Vessel** [comment]
Cool, thank you very much.
