### ISSUE TITLE
Support React 15.x

### ISSUE THREAD

**Issue by tyv** [PixelsCommander/ReactiveElements#59]
as far as I see you can safely update `package.json` with `^15.2.0` 
i've tried also to run tests but `gulp test` from master failed for me with this error: https://github.com/PixelsCommander/ReactiveElements/blob/master/src/reactive-elements.js#L7

**Comment by PixelsCommander** [comment]
Thanks, will have a look

**Comment by tyv** [comment]
I really tried to fix tests :) but seems like they are broken for a long term and probably better is to rewrite them

**Comment by PixelsCommander** [comment]
Yeah, true. Think it was broken when project was seriously refactored to use browserify and React 0.13

**Comment by PixelsCommander** [comment]
Thank you for efforts. I ll take care of it.

**Comment by tyv** [comment]
haha, so moving to 15 wouldn't be a problem :)

**Comment by tyv** [comment]
oh that was fast, here is small update PixelsCommander/ReactiveElements/pull/61

and would you mind to make release after?

**Comment by PixelsCommander** [comment]
@tyv Yeah, sure, released them both bower / npm
