### ISSUE TITLE
ability to wrap slate

### ISSUE THREAD

**Issue by joeblew99** [PixelsCommander/ReactiveElements#64]
Hey !
This looks awesome.

From the docs i get the impression that you cant just wrap any react element, without some changes to the React element ?

Take for example this:
https://github.com/ianstormtaylor/slate/tree/master/examples/hovering-menu

Is this wrappable with no changes to the react code ?

**Comment by PixelsCommander** [comment]
I would not say so. But it depends on API component provides and dependancies. You may try easily by yourself it takes few lines.
