### ISSUE TITLE
What did you do with the dist/reactive-elements.js packaging?

### ISSUE THREAD

**Issue by Elephant-Vessel** [PixelsCommander/ReactiveElements#65]
After updating reactive-elements, it breaks in my ecosystem due to `exports` being undefined. It looks like it's something to do with webpack. Do I have to use webpack? I have no interest in using webpack.

[This](https://github.com/PixelsCommander/ReactiveElements/commit/869831bf8f6fd005980588f766796c672b665bd6) commit changed it.

**Comment by PixelsCommander** [comment]
Which packager do you use?

**Comment by Elephant-Vessel** [comment]
none

**Comment by PixelsCommander** [comment]
There was an assumption that everybody uses webpack / browserify currently. You may roll back to previous NPM version until we take care of adding back compatibility for plain JS.

**Comment by Elephant-Vessel** [comment]
Yes, those packagers seem to be quite hyped today, but I've never felt any need to jump on that train. Reverting to 0.6.4 meanwhile :)

**Comment by PixelsCommander** [comment]
@tyv Could you add UMD wrapping to keep vanilla compatibility?

**Comment by tyv** [comment]
@Elephant-Vessel thanks for report.
@PixelsCommander yep, will do.

**Comment by tyv** [comment]
I think we should use UMD for `min.js` build only and `.js` is assuming that you want to use it with own builder and minimizer and I think right solution would be to left commonjs in this case.
