### ISSUE TITLE
registerReact() should return references to created react objects 

### ISSUE THREAD

**Issue by tlenex** [PixelsCommander/ReactiveElements#69]
It would be nice if I could interact with registered react object and element created by `registerReact()`.

Could `registerReact()` return something like example below?
```
return {
  'reactiveElementId':  { element: documentRegisterElementRef, reactObject: reactObjectRef}
}
```
or `Promise` with this data?

**Comment by jackfranklin** [comment]
@tlenex do you still need this ? I'm doing some admin so going to start closing up old issues; but let me know if this is still relevant :)

**Comment by jackfranklin** [comment]
Closing this, but @tlenex let me know if you'd like it opened.
