### ISSUE TITLE
New WebComponent spec requires class syntax

### ISSUE THREAD

**Issue by rektide** [PixelsCommander/ReactiveElements#71]
Hello,
The longstanding means of using `Object.create(HTMLElement.prototype)` to create Web Components was dropped in v1.0, and Chrome now throws an `Uncaught TypeError` if you try to use the current [ReactiveElements code](https://github.com/PixelsCommander/ReactiveElements/blob/4f47228655c07dcb8ed95fc2ebb26fc329778fb0/src/reactive-elements.js#L15).

For confirmation of this change, read:

> It's not possible to use custom elements without ES6 classes.

- Domenic, https://github.com/w3c/webcomponents/issues/587#issuecomment-253993830

This change is also impacting the WebComponenets demo in React itself. See facebook/react#8656.

**Comment by PixelsCommander** [comment]
Yeah, this is the thing to solve asap. The problem is that many react projects use babel and babel still have bug when trying to extend HTMLElement

**Comment by PixelsCommander** [comment]
https://github.com/babel/babel/issues/4480

**Comment by WebReflection** [comment]
FYI I've solved how I declare classes, explained in here:
https://github.com/babel/babel/issues/4480#issuecomment-272633118

**Comment by jackfranklin** [comment]
@PixelsCommander my understanding here is that once we move into Babel 7, we will be able to make this change. Is that correct?

**Comment by ChristianMurphy** [comment]
There is a work around to make Web Component v1 work without ES6 classes by applying https://github.com/github/babel-plugin-transform-custom-element-classes
