### ISSUE TITLE
Map the string attributes "true" and "false" to booleans

### ISSUE THREAD

**Issue by jackfranklin** [PixelsCommander/ReactiveElements#73]
So you can have a web component with `foo="true"` and the React component sees the boolean `true` or `false`. Would you be interested in a PR for that?

**Comment by PixelsCommander** [comment]
Sure, I would love to! 

This is something discussed before and found a bit iffy. What if it is a string intentionally? One of proposed ways to avoid ambiguity here is to have a flag "convertTypes" on a component level and globally.

**Comment by jackfranklin** [comment]
Yeah, would agree it should be opt in or opt out.

You could also (in development build) have a logged message when it happens. I would imagine 99% of the time people want `"true"` to represent the boolean version, maybe you could also pass a "reactive-elements-no-boolean" attribute flag or something.

**Comment by jackfranklin** [comment]
@PixelsCommander so I thought about this a bit more and I think we should introduce mapping of `'true'` and `'false'` *only* for now, and potentially consider if we should start mapping other things later on.

I think I'd like that behaviour to be *on by default* with the following behaviour:

- in development `(process.env.NODE_ENV === 'development')` it would log "converted attribute 'foo' to boolean true" or similar
-  in production there would be no logging
- passing an attribute of `reactive-elements-no-transform` would prevent any translation happening.
- if the attribute doesn't exactly match the string `'true'` or `'false'` it wouldn't be ignored (so things like `'False'` or 'F', etc, would be completely ignored).

I'm going to work on a PR for this soon :)

**Comment by PixelsCommander** [comment]
Sounds great!

**Comment by tonai** [comment]
Hi,
it would be great that the following code `<my-reactive-element selected />`would also set the props `selected` to `true`.

**Comment by jackfranklin** [comment]
@tonai I think that's a reasonable suggestion but I think it can be a separate PR / release. Would welcome a PR though :)
