### ISSUE TITLE
Releases not in sync with `npm`.

### ISSUE THREAD

**Issue by ryanpcmcquen** [PixelsCommander/ReactiveElements#77]
It seems that the latest release here (GitHub) was `0.6.5`, but `npm` has `0.6.8`. I find this a bit confusing. Is there a reason the release tags are not showing up on GitHub? Is the repo being hosted somewhere else?

**Comment by PixelsCommander** [comment]
Current version on GitHub is 0.6.8
https://github.com/PixelsCommander/ReactiveElements/blob/master/package.json#L3

Releases were supported for making it work for bower. Since bower is dead we do not see any need  to release further using tags.

**Comment by ryanpcmcquen** [comment]
I just think it is a good practice and makes it easy to tell when the last update was (without having to visit the npm site). I thought this project may be getting a bit stale and not compatible with React 16 at first glance, since the last 'release' I saw was in 2016. It was only later when I noticed the discrepancy in package versions between GitHub and npm that I realized releases were still happening.

**Comment by PixelsCommander** [comment]
@jackfranklin what do you think on releasing on GH?

**Comment by ryanpcmcquen** [comment]
The GitHub releases can also be a nice way to note changes. I do not see a current changelog for this library, so it can be difficult to know what changed (from `0.6.8` to `0.7.0` for instance).

**Comment by jackfranklin** [comment]
This is my bad, I missed a tag for 0.7.0. 0.8.0 includes it and I'll include it from going forward. @ryanpcmcquen you're right that a changelog would be useful for future releases, let's do it going forwards.
