### ISSUE TITLE
is this library works on browser env? 

### ISSUE THREAD

**Issue by obiwankenoobi** [PixelsCommander/ReactiveElements#94]
Hey! really cool tool! My use case for this library will be converting entire component so it could work on any HTML without the need to have React or node. I basically want to take the `build` file from my component and import the .js file inside any HTML and make it work. Is this library can do it? because I haven't seen any link to cdn so I wonder if it can even work without node env?

**Comment by ChristianMurphy** [comment]
> My use case for this library will be converting entire component so it could work on any HTML

Absolutely can be done.

> without the need to have React or node

It can run without Node, or without React, but not both.

**To use without Node:**

Add something like:

```html
<script src="https://unpkg.com/document-register-element@1.12.0/build/document-register-element.js"></script>
<script src="https://unpkg.com/react@16.6.0/umd/react.production.min.js"></script>
<script src="https://unpkg.com/reactive-elements@0.10.0/src/reactive-elements.js"></script>

<!-- add components here -->
```

**To use without React:**

Use a bundler (E.G. [webpack](https://webpack.js.org/) or [rollup](https://rollupjs.org/guide/en)) to combine React, document-register-element, and reactive elements into a single bundle file.

**Comment by jackfranklin** [comment]
Closing because I think your problem has been solved :)
