### ISSUE TITLE
Regex requires extra curly brace around json object

### ISSUE THREAD

**Issue by wharkins3** [PixelsCommander/ReactiveElements#95]
https://github.com/PixelsCommander/ReactiveElements/blob/7cce3d7b472989878ac1433cec0e8168fd4136aa/src/utils.js#L100

Is there a reason why the json is required to have an extra pair of curly braces? I noticed the unit tests string is written the same way
`var jsonSerialized = '{{"status": "active", "language": "javascript"}}'`

**Comment by ChristianMurphy** [comment]
The extra set of curly braces are used to differential an pointer expression from a json expression.

https://github.com/PixelsCommander/ReactiveElements/blob/7cce3d7b472989878ac1433cec0e8168fd4136aa/src/utils.js#L99-L119

**Comment by wharkins3** [comment]
Thanks for the response. Yes, we noticed that after looking through the source code. It might be helpful to put an example somewhere to save future users issues.

**Comment by ChristianMurphy** [comment]
> It might be helpful to put an example somewhere to save future users issues.

Pull requests are welcome!
Also consider adding thoughts to the discussion around improving the typecasting system #19
